name = "webchat"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = false

# Durable Objects bindings
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

# Routes for your domain
route = { pattern = "chat.890099.xyz/*", zone_name = "890099.xyz" }

# Or use workers.dev subdomain
# workers_dev = false

# Environment variables
[vars]
GITHUB_OWNER = "wsxxll"
GITHUB_REPO = "webchat"
GITHUB_BRANCH = "main"

[env.production]
vars = { ENVIRONMENT = "production", GITHUB_OWNER = "wsxxll", GITHUB_REPO = "webchat", GITHUB_BRANCH = "main" }