name = "webchat-core"
main = "chat-server.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Durable Objects bindings
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

# Environment variables
[vars]
ALLOWED_ORIGINS = "*"

[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://*.pages.dev,https://chat.890099.xyz"