name = "webchat"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

# Routes for your domain
# route = { pattern = "chat.example.com/*", zone_name = "example.com" }

# Or use workers.dev subdomain
# workers_dev = true

[env.production]
vars = { ENVIRONMENT = "production" }